import type { Metadata } from "next";
import { Archivo_Narrow, Geist, Geist_Mono } from "next/font/google";
import { Header } from "app/components/shared/Header";
import { Footer} from "app/components/shared/Footer"

import { Description } from 'app/components/home/Description'
import { Hero } from 'app/components/home/Hero';
import  'app/sass/globals.sass'
import {Roboto} from 'next/font/google'
import { afterEach } from "node:test";

const roboto = Roboto({
  weight: ["100","300","400","600","700",],
  subsets: ["latin"]
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Future World",
  description: "Generated by create next app",
  keywords:["ecommerce","future","videogames","world","living the present"]
};

export default function RootLayout({ children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body className={roboto.className}>
       <Header/>
       
        {children}
      <Footer/>
      </body>
    </html>
  );
}
  